spring:
  application:
    name: performancescholar
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/performancescholar
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true